# ########################################################### #
# Infinity Tower Plugin Developer: PopoGonry ( rhtjdsh35@gmail.com )
# ########################################################### #

# Infinity Tower Plugin Config File #

# Infinity Tower


Round-Score: 400

Round-Clear-Seconds: 1800

Allowed-Commands:

